apiVersion: v1
kind: Service
metadata:
  name: simple-cms-backend
  namespace: simple-cms
  labels:
    app: simple-cms-backend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: simple-cms-backend
---
apiVersion: v1
kind: Service
metadata:
  name: simple-cms-frontend
  namespace: simple-cms
  labels:
    app: simple-cms-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: simple-cms-frontend