apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-cms-backend
  namespace: simple-cms
  labels:
    app: simple-cms-backend
spec:
  selector:
    matchLabels:
      app: simple-cms-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 30s